DROP TABLE IF EXISTS Payroll;
DROP TABLE IF EXISTS LeaveRequests;
DROP TABLE IF EXISTS Attendance;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS AuditLogs;
DROP DATABASE PayrollDB;
